version: '3'
services:
  nginx:
    build:
      context: docker
      dockerfile: ./nginx/Dockerfile
    volumes:
      - .:/var/www/symfony/
    ports:
      - "80:80"
    networks:
      - net
    depends_on:
      - php
  php:
    build:
      context: docker
      dockerfile: ./php/Dockerfile
    volumes:
      - .:/var/www/symfony/
    networks:
      - net
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # web ui
    networks:
      - net

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=efficience
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5435:5435"
    networks:
      - net

volumes:
  db-data: {}

networks:
  net: